-----------------------------------------------
-- 1. Find customers from Chennai
SELECT *
FROM customers
WHERE city = 'Chennai';

------------------------------------------------

-- 2. Find products with price greater than 10000
SELECT *
FROM products
WHERE price > 10000;

------------------------------------------------

-- 3. Count total number of customers
SELECT COUNT(*) AS total_customers
FROM customers;

------------------------------------------------

-- 4. Count total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;

------------------------------------------------

-- 5. Find the most expensive product
SELECT *
FROM products
WHERE price = (
    SELECT MAX(price)
    FROM products
);

------------------------------------------------

-- 6. Find the cheapest product
SELECT *
FROM products
WHERE price = (
    SELECT MIN(price)
    FROM products
);

------------------------------------------------

-- 7. Calculate total revenue generated from all orders
SELECT SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id;

------------------------------------------------

-- 8. Display customer names and their orders using JOIN
SELECT c.customer_name,
       o.order_id,
       o.order_date
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

------------------------------------------------

-- 9. Display product names purchased by each customer
SELECT c.customer_name,
       o.order_id,
       p.product_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN products p
ON o.product_id = p.product_id;

------------------------------------------------

-- 10. Find total quantity sold for each product
SELECT p.product_name,
       SUM(o.quantity) AS total_quantity
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name;

------------------------------------------------

-- 11. Find total revenue generated by each product
SELECT p.product_name,
       SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name;

------------------------------------------------

-- 12. Find the top-selling product
SELECT p.product_name,
       SUM(o.quantity) AS total_quantity
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 1;

------------------------------------------------

-- 13. Find the customer who spent the most money
SELECT c.customer_name,
       SUM(o.quantity * p.price) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 1;

------------------------------------------------

-- 14. Find total sales by product category
SELECT p.category,
       SUM(o.quantity * p.price) AS total_sales
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category;

------------------------------------------------

-- 15. Find average product price by category
SELECT category,
       AVG(price) AS average_price
FROM products
GROUP BY category;

------------------------------------------------

-- 16. Find customers who placed more than one order
SELECT c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING COUNT(o.order_id) > 1;

------------------------------------------------

-- 17. Find monthly sales revenue
SELECT DATE_TRUNC('month', o.order_date) AS month,
       SUM(o.quantity * p.price) AS revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY month
ORDER BY month;

------------------------------------------------

-- 18. Find the city with the highest number of customers
SELECT city,
       COUNT(*) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC
LIMIT 1;

------------------------------------------------

-- 19. Find the top 5 customers by spending
SELECT c.customer_name,
       SUM(o.quantity * p.price) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 5;

------------------------------------------------

-- 20. Find products that have never been ordered
SELECT p.product_name
FROM products p
LEFT JOIN orders o
ON p.product_id = o.product_id
WHERE o.product_id IS NULL;

--------------------------------------------------

-- 21. Show all customers sorted by join date
SELECT *
FROM customers
ORDER BY join_date;

--------------------------------------------------

-- 22. Show products sorted by price (highest first)
SELECT *
FROM products
ORDER BY price DESC;

--------------------------------------------------

-- 23. Find total number of products in each category
SELECT category,
       COUNT(*) AS total_products
FROM products
GROUP BY category;